---
engines:
 duplication:
   enabled: true
 metric:
   enabled: true
 coverage:
   enabled: true
   exclude_paths:
     - config/engines.yml
exclude_paths:
  - '.*'
  - '*.md'
  - '*.json'
  - '*.css'
  - 'node_modules/**'
  - 'doc/**'
  - 'coverage/**'
  - '.nyc_output/**'
  - 'test/**'