sudo: false
language: node_js
node_js: "10"
services: 
  - postgresql
addons:
  postgresql: "9.6"
cache:
  directories:
  - node_modules
notifications:
  email: false
install:
  - npm install
script:
  - npm run test
after_success:
  - npm run coveralls
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: heroku
  api_key: 759e2259-6ed8-413b-86d7-9122e01dc383
  app:
    develop: wayfarertest